language: python
python:
    - "2.6"
    - "2.7"

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq libfreetype6-dev libblas-dev libgfortran3 build-essential gfortran liblapack-dev
    - sudo apt-get install -qq graphviz graphviz-dev

install:
    # install dependencies
    - pip install -r requirements.txt
    - pip install coveralls
    # compile cpp files
    - cd sparse; make all; cd ..;

before_script:
    - export PYTHON_PATH=$PYTHON_PATH:$(pwd)

script: coverage run --source=sparse test.py

after_success: coveralls
